### ISSUE TITLE
maybe support for a bulk?

### ISSUE THREAD

**Issue by mainpart** [michaelcarter/mixpanel-data-export-js#5]
Hello. I found undocumented user deleteon feature 
http://stackoverflow.com/questions/19049621/mixpanel-bulk-delete-old-users
it comes with POST method for bulk events. Maybe it's worth implementation?

**Comment by michaelcarter** [comment]
@mainpart I'm aware this has taken me an incredibly long time to get back on, sorry. 

I'm not going include this right now because it's not part of the documented API, meaning I'd be opening myself up to issues if it were to change or remove under my feet. If loads more people ask for it I'll consider it further.

Thanks for the suggestion though, and for making me aware this exists!
