### ISSUE TITLE
maybe csv format support?

### ISSUE THREAD

**Issue by areagray** [michaelcarter/mixpanel-data-export-js#8]
Hi.  Looks like the event csv format parameter causes it to error out, json works like a charm.  Would be super to have that support since Mix is already doing the work.  

http://d.pr/i/1aJ4i

Thanks for considering - very helpful lib.

**Comment by michaelcarter** [comment]
@areagray. A long time coming but I've just published an update to pass through a csv string if you specify `format: 'csv'` formatting in your request parameters. This doesn't work in-browser at the moment because the script doesn't expect the `text/csv` content type, but should be fine in nodey environments.

Perhaps you could give it a try and let me know if it's what you'd expected?

**Comment by areagray** [comment]
thanks mike! will try to take it for a test run this week....

**Comment by michaelcarter** [comment]
@areagray Any thoughts on this? I'll close the issue this weekend and hope for the best unless I hear from you. :-)

**Comment by areagray** [comment]
Hi Mike!

I'm sorry I haven't tested it.  I've been working with your lib all day,
actually.  I've been using it in meteor.js to do some processing with the
people data.  Interesting thing - unlike event data, which returns with no
limit, engage data is paged.  So, to get more than 1000 users back, i
needed to create a version of a promises array to to manually page through
the results, then return when all complete.  Fun day.

Thanks again for creating this awesome utility.

Chris

**Comment by areagray** [comment]
Hi Michael,

I noticed I've started getting error messages back from Mix saying "Expired
request" .  Have you seen this recently?

Thanks for the insight,
Chris G

**Comment by areagray** [comment]
disregard - figured out how to change the default timeout.  cheers.
